### ISSUE TITLE
有个建议麻烦看一下

### ISSUE THREAD

**Issue by blueberrycan** [XUANXUQAQ/File-Engine#1]
能把打开的快捷方式设置成快速按两下ctrl吗，这样比较方便，还有就是打开搜索框之后可以点击esc退出，而不只是点搜索框外退出，做的特别好，希望可以坚持下去

**Comment by XUANXUQAQ** [comment]
感谢支持！！后续会考虑做点击两下ctrl打开的，关闭搜索框不只是点击搜索框外才能退出，再点一次快捷键(Ctrl + Alt + K)也能关闭
