### ISSUE TITLE
提问

### ISSUE THREAD

**Issue by getshellbypass** [XUANXUQAQ/File-Engine#11]
您好，我想只获取到所有文件的路径，然后放在一个db文件中，我是不是只需要编译fileSearcherUSN 文件夹

**Comment by XUANXUQAQ** [comment]
是的，不过因为fileSearcherUSN是和主程序配合使用的，File-Engine是通过在user/MFTSearchInfo.dat中写入需要搜索的信息，然后由fileSearcherUSN读取并进行搜索，为了实现高速搜索，默认是每一个磁盘创建一个数据库，并通过多线程并发搜索。如果你想要存在一个db文件中，需要修改一下内部存储的逻辑。
