### ISSUE TITLE
有 linux 支持吗？

### ISSUE THREAD

**Issue by taotieren** [XUANXUQAQ/File-Engine#12]

**Comment by XUANXUQAQ** [comment]
暂时没有，因为原生库中大量使用了Windows API，并且高速搜索也依赖于Windows的NTFS文件系统，我一个人维护也有点麻烦，大学期间也比较忙，所以暂时可能不会做Linux的支持。所有的原生库都是使用jni实现的，如果感兴趣的话也可以自己做，欢迎pr。
