### ISSUE TITLE
为什么要使用ascii码和对文件进行分组存储？

### ISSUE THREAD

**Issue by fh1999** [XUANXUQAQ/File-Engine#14]
Hi，请教一下代码的分组存储逻辑，
collect_result_to_result_map函数通过文件名的ascii值之和，将其划分到41个不同的桶里面，与数据库相对应。

为什么需要分多个表呢？是为了加速运算吗？为什么通过文件名的ascii和进行划分？

期待作者答疑！

**Comment by XUANXUQAQ** [comment]
这里其实是一个经验数据，划分了41个组主要是由于当ascii值的和超过4100之后就几乎都是一些文件名超长的缓存文件，基本对用户没什么用，这里命名仍然用的是ascii，实际上搜索时使用的是utf-8编码（本人C++水平并不高，写的代码也不太规范。。）划分这么多表也是利用分表来实现多线程加速搜索，当不打开GPU加速时，在Java中采用了线程池任务提交的机制来实现搜索，小任务完成速度比较快，采用CachedThreadPool可以使线程的复用率更高，从而节省资源，划分多个子任务也有利于任务及时停止，避免用户在快速输入时无法及时停止掉之前的任务导致卡顿。
在GPU加速的数据存储也使用这些表的名称进行了分组，通过磁盘盘符，数据对应的表名，以及文件后缀名的优先级进行分组（例如一个文件C:\test.exe，在显存中就会存储在[C,list7,9]这个块中），在GPU启动核函数进行搜索时，就可以将一个大的搜索任务分配为多个小任务，便于任务的及时停止。

**Comment by XUANXUQAQ** [comment]
> 这里其实是一个经验数据，划分了41个组主要是由于当ascii值的和超过4100之后就几乎都是一些文件名超长的缓存文件，基本对用户没什么用，这里命名仍然用的是ascii，实际上搜索时使用的是utf-8编码（本人C++水平并不高，写的代码也不太规范。。）划分这么多表也是利用分表来实现多线程加速搜索，当不打开GPU加速时，在Java中采用了线程池任务提交的机制来实现搜索，小任务完成速度比较快，采用CachedThreadPool可以使线程的复用率更高，从而节省资源，划分多个子任务也有利于任务及时停止，避免用户在快速输入时及时停止掉之前的任务。 在GPU加速的数据存储也使用这些表的名称进行了分组，通过磁盘盘符，数据对应的表名，以及文件后缀名的优先级进行分组（例如一个文件C:\test.exe，在显存中就会存储在[C,list7,9]这个块中），在GPU启动核函数进行搜索时，就可以将一个大的搜索任务分配为多个小任务，便于任务的及时停止。

显存中之所以采用这样编码成[C,list7,9]一个大块来进行对应表字符串的存储，而不是每个字符串都使用cudaMalloc()进行存储，是因为cudaMalloc()函数每次分配一块显存，都会占用一点系统内存，大概是用来保存分配的一些具体信息，以供cudaFree()和其他函数来使用。所以如果每个字符串都单独分配一小块显存，将会占用大量的系统内存。但是如果所有的字符串都放进一个块中又会导致核函数每次都会搜索所有的字符串，效率较低。

在GPU加速的两个框架中，cuda版本和opencl版本的存储方案略有不同，opencl1.2不支持在核函数中使用size_t，无法进行内存寻址操作，所以opencl版本每个字符串都是等长的，cuda版本字符串是变长的，通过另一个size_t数组保存字符串的长度，所以显存使用率要高一些。
