### ISSUE TITLE
可用性不如everything

### ISSUE THREAD

**Issue by KnIfER** [XUANXUQAQ/File-Engine#16]
才开始的项目吧，可用性太差了。

启动后只有一个设置界面，字体布局一言难尽，要按快捷键才出现搜索框。。。

---

我理解开源项目才开始，功能有就行。

这里描述一下个人使用场景，以及everything利弊，以供参考。

+ Everything 当文件管理器，可以搜索、聚合来自不同drive，不同目录的文件。它还可以放大预览网格。
+ Everything 可监控文件变化，尤其c盘，这点在“尝试运行新ide或他人项目时”很有用，可以监控c盘多了哪些文件，以便清理。
- Everything 无法真正排除磁盘索引，只能排除搜索。它总是会自动索引新插入的磁盘，即使配置exclude也没用。我的一个盘都快用废了还给我扫描，扫描成了未响应。。。

---

编译很复杂？Java是纯做界面还是参与搜索逻辑，等我再把磁盘清理十个g（刚清理的又被idea吃光了），有空再试试。

有没有纯c++的原始一点的demo。。

**Comment by KnIfER** [comment]
我丢，原来 Everything 支持排除磁盘索引。刚刚注册了论坛，没想到作者秒回，解决了问题。

https://www.voidtools.com/forum/viewtopic.php?t=14818

隐藏够深。。

现在 Everything 只剩利而无弊，告辞！

**Comment by XUANXUQAQ** [comment]
这个项目只有我一个人维护，以前高中的时候拿Java Swing写的GUI，现在没什么动力来改UI了。功能性方面确实不如everything。

**Comment by KnIfER** [comment]
可以试试 idea 的界面体系，kotlin写界面，够新颖。很好编译。https://github.com/JetBrains/intellij-community
