### ISSUE TITLE
用的过程中有点问题，大佬有空看下

### ISSUE THREAD

**Issue by tigeedev** [XUANXUQAQ/File-Engine#2]
系统Win10，电脑安装了 Everything、Clover、uTools等软件。
软件在后台正常运行，鼠标放在某个文件上后，上方会出现一个小透明框（我试了，不是搜索框），有时候还会一直闪。软件退出后就不见了（难道是和我安装的其他软件有冲突吗？？？）

![问题](https://user-images.githubusercontent.com/58299289/105191439-08fb0500-5b72-11eb-90f5-e47c97245ae1.gif)

**Comment by XUANXUQAQ** [comment]
emm，那个其实就是搜索框..
这可能是因为Clover的原因，因为该软件会检测资源管理器窗口并尝试贴靠在上面，而Clover会使一个窗口内有多个explorer的句柄，导致程序识别出现问题
[![sfwgyR.png](https://s3.ax1x.com/2021/01/20/sfwgyR.png)](https://imgchr.com/i/sfwgyR)

**Comment by tigeedev** [comment]
好了解决了，把Clover卸载后就不会闪了，就是上方的搜索框一直靠着，看着有点奇怪哈哈

![image](https://user-images.githubusercontent.com/58299289/105262572-23150180-5bcb-11eb-8ec4-6586588e164d.png)
