### ISSUE TITLE
初次使用体验和建议

### ISSUE THREAD

**Issue by wordpure** [XUANXUQAQ/File-Engine#3]
![image](https://user-images.githubusercontent.com/68013962/105569904-d83cea80-5d80-11eb-9e70-b933e5d3fb3a.png)

![image](https://user-images.githubusercontent.com/68013962/105569911-e3901600-5d80-11eb-8bc7-c8251f808fe7.png)

![image](https://user-images.githubusercontent.com/68013962/105569918-e8ed6080-5d80-11eb-9233-ae2971ef4230.png)

![image](https://user-images.githubusercontent.com/68013962/105569932-f276c880-5d80-11eb-8cd6-e7da28d4b801.png)

![image](https://user-images.githubusercontent.com/68013962/105569933-f571b900-5d80-11eb-938c-b885edd05780.png)

**Comment by wordpure** [comment]
搜索功能和样式建议参照 [Listary 6 Beta](https://discussion.listary.com/t/listary-6-beta/4615) 和 [Vivaldi](https://vivaldi.com/zh-hans/) 的快捷命令。

![image](https://user-images.githubusercontent.com/68013962/105570148-5057e000-5d82-11eb-91ff-d3068240924d.png)

![image](https://user-images.githubusercontent.com/68013962/105570061-cc9df380-5d81-11eb-9c85-d744f4c91472.png)

**Comment by wordpure** [comment]
设置界面建议参照 [Everything](https://www.voidtools.com/zh-cn/)、TIM 或 QQ、Vivaldi。

![image](https://user-images.githubusercontent.com/68013962/105570319-919cbf80-5d83-11eb-9b51-262532f15cb9.png)

![image](https://user-images.githubusercontent.com/68013962/105570323-9cefeb00-5d83-11eb-8534-223d50e2f698.png)

![image](https://user-images.githubusercontent.com/68013962/105570324-a0837200-5d83-11eb-9cd8-156ca5fe5d04.png)

**Comment by XUANXUQAQ** [comment]
非常感谢您的反馈呀，您这么细心都不知道说什么好了！！就一个个回答一下吧。
1. 关于超长文本，我现在也是在寻找解决方案，现在是使用html来实现自动换行，我会尝试一下您的建议，如果成功了，下个版本就会进行更新。

2. 下个版本就会添加手动关闭这个功能的，让用户自己选择是手动呼出还是进行贴靠，其实这个功能本身不只是贴靠在资源管理器上单纯的进行搜索，这个功能主要是用在选择文件的时候，比如浏览器选择图片上传，或者QQ发送文件，这个窗口可以贴靠在文件选择窗口上，从而进行快速选择。
[![sTTBI1.png](https://s3.ax1x.com/2021/01/23/sTTBI1.png)](https://imgchr.com/i/sTTBI1)

3. 这个搜索框是根据用户的屏幕分辨率大小来自动适配的，我会在下个版本将它缩小一点。

4. 设置界面我自己也认为确实有点丑。。我会采纳你的建议，下个版本将会对设置界面进行改进。

5. 关于语言：因为Java Swing本身的限制问题，貌似采用不同语言时系统托盘会乱码，因为Java虚拟机中我设置的编码是UTF-8，而Windows默认是GBK，会导致显示不出来文字的问题，而且目前也没有找到什么解决方案，如果您知道一些解决方案的话，请务必告诉我。

当然了，作为一个普通的大一学生，因为学业的问题，而且这个项目只有我一人维护，可能更新不会太快，还请见谅。

最后，再次感谢您的反馈，我会认真阅读，并且不断改进。

**Comment by wordpure** [comment]
另外，希望作者能思考下 File-Engine 和其他同类软件，如 Listary、[Wox](http://www.wox.one/) 等相比，它的特质何在？

如果只是搜索速度更快、可自定义程度更高的话，可能还不足以让大多数同类软件的用户改变他们的使用习惯 🤦‍

**Comment by wordpure** [comment]
文件定位是一个很实用的功能，但或许将文件选择窗口和资源管理器内搜索，分为两个使用情景会比较好一点。

在浏览器或聊天软件打开的文件选择窗口，选择文件是目的，快速定位文件夹位置、选择文件是痛点。这时，显示搜索框是提高效率的需要。

但在资源管理器窗口，切换文件夹、定位文件不再是首要目的，创建、移动、删除文件等才是高频操作，因而显得搜索框碍眼。

这是不同时期的需求不同导致的，手动选择呼出或贴靠，对提高这两种情景下的效率似乎也没有多大帮助。

另外，软件打开的文件选择窗口，位置通常都在屏幕中间，用户通常也不会手动改变它的大小，因此搜索框贴靠在左上方是可行的。

但是对资源管理器来说就不一样了，用户经常会根据使用情景改变它的大小、位置，如常见的全屏、二分屏。如果还贴靠在资源管理器外侧的话，可能就完全看不见搜索框了。

**Comment by wordpure** [comment]
据我观察，目前的文件定位方式，似乎是将焦点所在的文件或文件夹路径，以模拟 `Ctrl + V`  的方式发送到资源管理器窗口实现的。

但这样有几个问题。

1. 会污染剪贴板；
2. 只能定位到文件所在的文件夹，不能精确地定位文件位置；
3. 速度略慢；
4. 有一些奇奇怪怪的 BUG
    - 文件定位功能在资源管理器窗口、浏览器打开的文件选择窗口失效；
    - 定位部分文件，如 C:\Users\<Username>\AppData\Roaming\Microsoft\Windowss\Recent 目录下的文件时，会提示没有权限，但你的权限本来是够的，而且通过该窗口的地址栏访问就不会报错。

**Comment by wordpure** [comment]
大一就能够自己做出这样的作品，很厉害 👍

作者愿意花费时间、精力，开发和维护开源软件，就已经很好了，更新频率不是什么问题。

也祝 File Engine 越做越好，作者技术精进，学业有成

**Comment by XUANXUQAQ** [comment]
感谢反馈。我会按照你的建议，对软件进行改进。
1. 关于剪贴板的问题，在设计之初就考虑了污染的问题，现在文件定位虽然是模拟 `Ctrl + V` 来实现的，但完成后会还原之前的内容，所以不存在污染的问题。

2. 只能定位到文件夹，不能定位到文件的问题，我也在想解决方案，但是目前还没有什么头绪。

3. 关于bug：
    windows系统好像不允许软件操控鼠标键盘来访问用户文件夹，必须是由用户的外设发出的中断才能访问。
后续我会想想解决办法，尽量把这个问题解决。

**Comment by wordpure** [comment]
可能我们对于「污染剪贴板」的理解不太一样 🤦‍

软件确实会还原先前的内容，不会影响正常的复制、粘贴操作。

只是我在用剪贴板管理软件，所以对写入剪贴板的行为比较敏感。

![image](https://user-images.githubusercontent.com/68013962/105577209-06d3b900-5db3-11eb-8cb9-35b28bd6db61.png)

**Comment by wordpure** [comment]
关于文件定位，Windows 有提供一些 API 供开发者调用，或者可以往这方面考虑。

[ShellExecute API详解。通过在资源管理器(explorer)中打开文件夹和在默认浏览器中打开url链接等_iMatt的专栏-CSDN博客](https://blog.csdn.net/iMatt/article/details/106156986)

[ShellExecuteA function (shellapi.h) - Win32 apps | Microsoft Docs](https://docs.microsoft.com/en-us/windows/win32/api/shellapi/nf-shellapi-shellexecutea)

**Comment by wordpure** [comment]
我对 Java 编程不是很了解。

不过刚才搜索乱码问题的时候看到了下面的这篇文章，虽然年代可能比较久远，但或许对你有所帮助。

[MenuItem 显示中文乱码问题解决方案 - Java编程思想的个人空间 - OSCHINA - 中文开源技术交流社区](https://my.oschina.net/u/1157906/blog/169442)

**Comment by XUANXUQAQ** [comment]
> 我对 Java 编程不是很了解。
> 
> 不过刚才搜索乱码问题的时候看到了下面的这篇文章，虽然年代可能比较久远，但或许对你有所帮助。
> 
> [MenuItem 显示中文乱码问题解决方案 - Java编程思想的个人空间 - OSCHINA - 中文开源技术交流社区](https://my.oschina.net/u/1157906/blog/169442)

太感谢你的资料了，中文乱码的问题已经解决！

**Comment by KnIfER** [comment]
Listary 就是个鸡肋，我不会编程的时候就安装卸载过，会点编程后又安装卸载过。不明白为什么这么火。

powertools我也安装卸载过，感觉应用启动类的都有点鸡肋，还大。
常用程序就那几个，与其用别人的启动器，不如添加自启、添加ahk快捷键来的实用。
安卓的“快启动”可以拼音搜索倒是挺有用、好玩的，还小。

explorer 就那样有啥好增强的。。有用是有用，再增强也就那样。。。不必趋之若鹜。
比方说我写的一个文件管理器，可以各种分组聚合（日期/前缀/后缀/标签名），可以各种排序，可以直接搜索列表，根本用不着别人增强。
