### ISSUE TITLE
出现搜索框无法关闭的bug

### ISSUE THREAD

**Issue by jary0218** [XUANXUQAQ/File-Engine#5]
在下载文档选择保存路径时，弹出了搜索框并且无法关闭，搜索框显示的位置无法改变并且遮挡住了弹窗的“最小化、关闭”
另外在其他软件弹窗保存路径时也会有这个bug，
不如在这种情况下，将搜索框直接放在保存路径弹窗的最底端

**Comment by jary0218** [comment]
并且在该搜索框中输入保存路径时不能跳转到制定路径

**Comment by XUANXUQAQ** [comment]
下一个版本中搜索框的位置已经改到下方，目前还在进行测试中

**Comment by jary0218** [comment]
ok.希望越做越好~~

**Comment by jary0218** [comment]
每次开机都提醒不要安装在C驱动盘，但是我没有安装在C驱动盘里，
另外出现bug：在我打开资源管理器时就会自动弹出搜索框
