### ISSUE TITLE
使用建议和优化体验

### ISSUE THREAD

**Issue by hawkDR** [XUANXUQAQ/File-Engine#6]
1.首次启动，需要的java环境希望改进（最好是能启动直接可以使用），第一次启动就出现错误，如果没有耐心大部分体验不好就不会往下折腾JDK了。
![图片](https://user-images.githubusercontent.com/47166422/110091338-4ee2f400-7dd3-11eb-9402-8899372df2de.png)
2.希望增加搜索文件的右键选项功能。
3.插件功能下载失败，挂代理也是下载失败

**Comment by XUANXUQAQ** [comment]
感谢反馈，Java环境是在File-Engine-x64.V{版本号}.exe中集成了的，这是一个自解压文件，如果直接下载File-Engine-x64.exe则需要电脑自带Java环境，或者只需要在File-Engine-x64.exe所在目录将Java运行环境复制过来，并将文件夹命名为jre即可。

**Comment by hawkDR** [comment]
> 
> 
> 感谢反馈，Java环境是在File-Engine-x64.V{版本号}.exe中集成了的，这是一个自解压文件，如果直接下载File-Engine-x64.exe则需要电脑自带Java环境，或者只需要在File-Engine-x64.exe所在目录将Java运行环境复制过来，并将文件夹命名为jre即可。

刚才重新下载试了，可以了。感谢
建议：备注下（带运行环境）或者（不带运行环境）
