### ISSUE TITLE
调用CMD提示错误

### ISSUE THREAD

**Issue by qiuguangyuan9** [XUANXUQAQ/File-Engine#7]
调用cmd命令错误提示：Windows找不到文件 'pl"ugins/Plugin configuration files/Cmd/tmp\$$bat.bat""。请确定文件名是否正确后，再试一次。   win10家庭版

**Comment by XUANXUQAQ** [comment]
感谢你的反馈，问题已经修复，麻烦你更新下插件。推送可能有点慢，你也可以直接替换plugins文件夹中的jar文件。
[Cmd.zip](https://github.com/XUANXUQAQ/File-Engine/files/6186886/Cmd.zip)
